### ISSUE TITLE
Doesn't seem to work with Yosemite (OS X v10.10) Color Picker 

### ISSUE THREAD

**Issue by rmm5t** [TylerEich/Alfred-Extras#18]
The OSX color picker still launches as before, but upon selecting a color, the colors workflow no longer recognizes the selection.

**Comment by anurag-banerjee** [comment]
I've had the same issue, and I came up with a workaround for it. Press the option key before pressing the color picker button. This will allow you to press the choose button afterwards and pass that information back to Alfred.

Installing 2.0.1 didn't fix the issue though.

**Comment by pochemuto** [comment]
same issue, 2.0.1 didn't fix that

**Comment by TylerEich** [comment]
Good to know. Right now, I can't get Xcode to compile the codebase at all, even the ones that worked previously.

If anyone has a copy of the project that Xcode can compile, I would love some help. I can't begin to debug when I can't even run the code I'm writing 😒.

If Xcode continues to be so unpredictable, I may have to find another way to fix this workflow, which could take a significant amount of time.

Tyler Eich • tyler2eich@gmail.com

On May 19, 2015, at 12:28 PM, Александр Крамарев <notifications@github.com> wrote:

same issue, 2.0.1 didn't fix that

**Comment by cucumbur** [comment]
I don't even use the dropper and it still won't work. It's such an old project that Im sure it wont ever get fixed... but im too dumb to figure out mac internal stuff (maybe I should learn)
