### ISSUE TITLE
Brutal CPU usage with colors

### ISSUE THREAD

**Issue by elado** [TylerEich/Alfred-Extras#19]
![screen shot 2014-11-11 at 10 49 21 pm](https://cloud.githubusercontent.com/assets/51488/5006749/5dac2138-69fc-11e4-9abe-13426d774290.png)

These processes show up randomly after using the workflow. It's killing the CPU.

**Comment by anurag-banerjee** [comment]
I've had the same issue, and I came up with a workaround for it. Press the option key before pressing the color picker button. This will allow you to press the choose button afterwards and pass that information back to Alfred.

**Comment by TylerEich** [comment]
I've updated this workflow to v2.0.1 on Packal. Could you try v2.0.1 and see if it resolved your issue?

http://www.packal.org/workflow/colors
