### ISSUE TITLE
Swift syntax in Colors workflow

### ISSUE THREAD

**Issue by thomasdegry** [TylerEich/Alfred-Extras#21]
Any update on adding swift color support to the workflow?

**Comment by TylerEich** [comment]
Right now, my plan is to first add a few extra output formats to support swift, which won't be difficult. Next, I'll add support for parsing Swift color formats and a quick-and-dirty script filter so users can convert from Swift. That should end up in Colors v2.1.

I'm also laying some **tentative** plans for Colors 3.0, possibly including rewriting the entire workflow in Swift (Objective-C is a pain) and letting users specify their own preferred color formats and outputs using a regex-esque syntax in a JSON configuration file.

For now though, adding some basic Swift support is a priority whenever I have time to work on the codebase. Pull requests welcome :smile:

**Comment by thomasdegry** [comment]
Cool sounds great! Will take a look at it when I have some free time 👍

**Comment by thomasdegry** [comment]
Any clue why this is happening? 

dyld: Library not loaded: ./Alfred.framework/Versions/A/Alfred
  Referenced from: /Users/LOANER/Library/Developer/Xcode/DerivedData/colors-hhimzvfmzwcsgsfphwhovyxcjmwk/Build/Products/Debug/colors
  Reason: image not found

**Comment by TylerEich** [comment]
Because Xcode is a jerk 😒

3ad1eef89cdccdb2ef6873a32cccd088f4146247 should resolve this issue. Thanks for giving this a go!

**Comment by TylerEich** [comment]
v2.1 is available for beta testing: #25
