### ISSUE TITLE
Favorites workflow

### ISSUE THREAD

**Issue by jousch** [TylerEich/Alfred-Extras#23]
Hi Tyler,

thanks for the nice favorite workflow! Is it technically possible to add the actual folder in iterm tab?

cheers
josef

**Comment by TylerEich** [comment]
If you mean "Can I `cd` into the folder of this workflow?", yes you can! 

Open iTerm. Type `cd `. Then find the Colors workflow in Alfred's preferences. Right click on it in and choose "Show in Finder". Drag the folder from Finder into iTerm.

That should do it 😊

Tyler Eich • tyler2eich@gmail.com

On May 21, 2015, at 3:44 AM, Josef Florian Glatz <notifications@github.com> wrote:

Hi Tyler,

thanks for the nice favorite workflow! Is it technically possible to add the actual folder in iterm tab?

cheers
josef
