### ISSUE TITLE
[Beta testers needed] Colors v2.1

### ISSUE THREAD

**Issue by TylerEich** [TylerEich/Alfred-Extras#25]
Hello all! I'm preparing to release an update for Colors that supports the Swift syntaxes for NSColor and UIColor. This is the only major change to the codebase, and the only one that needs testing.

If you'd like to help test it, you can download the latest beta here: http://cl.ly/1K2R231R3P1V

Let me know how you get on!

Bugs found:
- [x] ~~When using `[ns` (or any of the OSX/iOS commands) the color is not shown on the left of the snippet, where the icon is supposed to go, but if rgb is used, then the icon has the correct color~~

**Comment by pennatil** [comment]
Tried on 10.10.4, Issue #18 is still present. Whenever  I do Alfred-> [ns -> choose, the panel disappears and does not allow you to choose the correct one from the list, even when using the option button. Before it showed the options with 0 for all the values. If you post the build process you are using, I might be able to help.

**Comment by TylerEich** [comment]
@pennatil Two of the three bugs you listed actually are the intended behavior. The snippet is supposed to paste when you select it, and all available color conversions are displayed regardless of the input format. Alfred will organize them according to which ones you frequently use.

I think the latest build should fix your second reported bug: http://cl.ly/1K2R231R3P1V

**Comment by pennatil** [comment]
@TylerEich That did it! the colours are now shown correctly. Do you think there is a chance to implement a preference to avoid showing all possible representations? This would unclutter the list quite a bit

**Comment by TylerEich** [comment]
I have a **very** fuzzy idea of the feature set for Colors v3.0. Among the features I hope to add is a user-customizable list of color syntaxes to parse from and output to. So if a user doesn't use Objective-C color formats at all, they can remove those entries from their configuration and those formats won't be parsed or be available in the results. I don't have any plans to let the user specify "when I use format X, respond with formats A, B, and C"
