### ISSUE TITLE
Colors appears to be broken in el capitan

### ISSUE THREAD

**Issue by danielecook** [TylerEich/Alfred-Extras#27]
Specifically, picking a color only sometimes works e.g. white works, most colors do not.

**Comment by TylerEich** [comment]
Just to confirm, you are using the latest version? I'll investigate this later today.

v2.0.2 http://www.packal.org/workflow/colors

**Comment by danielecook** [comment]
Yes v2.02. Thanks!

**Comment by TylerEich** [comment]
Just out of curiosity, have you tried [the 2.1 beta](https://github.com/TylerEich/Alfred-Extras/issues/25)? It might fix your issue…

**Comment by danielecook** [comment]
Unfortunately - no - this doesn't resolve the issue.

**Comment by TylerEich** [comment]
I think I've replicated the issue; does it display a blank window after you choose from the color picker?

**Comment by danielecook** [comment]
Yes - this is what I observe.

![](http://cl.ly/image/2u3g071A2T1b/Screen%20Shot%202015-10-14%20at%2011.29.15%20AM.png)

**Comment by TylerEich** [comment]
Hmmmm. I've just tried to replicate the issue again and I can't. Can you find a specific color (any color) that I can type into Alfred that will consistently cause this behavior? I'm sorry to ask about this; I'm not sure why I can't get it to happen again…

**Comment by danielecook** [comment]
Try selecting "aqua"

<img width="440" alt="screen shot 2015-10-14 at 8 33 46 pm" src="https://cloud.githubusercontent.com/assets/1536935/10502552/e2a9cc54-72b2-11e5-9861-208532c72732.png">

Then try selecting snow white - upper right corner.

selecting white works...selecting aqua does not.

**Comment by danielecook** [comment]
Upgrading to the latest version of Alfred appears to have fixed the issue! Sorry about that!

Thanks,
Dan

**Comment by TylerEich** [comment]
No worries, thanks for reporting it 😎👍
