### ISSUE TITLE
[*Versions* Alfred workflow] Reading binary .plists fails

### ISSUE THREAD

**Issue by Jyqft** [TylerEich/Alfred-Extras#28]
The code for the _Versions_ Alfred workflow seems to assume that the app's .plist file is in xml format, which works for a lot of the apps around. However, there are a few apps out there whose .plist files are in binary format—and thus, using the workflow on these apps fails to yield the proper output.

If possible, there should be provisions in the code for cases wherein the .plist is in binary format.

**Comment by TylerEich** [comment]
Thanks for pointing this out. I'll see if the built-in OS X utilities support binary plist files

**Comment by Jyqft** [comment]
There's [`plutil`](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/plutil.1.html), which can convert between binary and xml plists.

Not sure how this can be incorporated into the code in an un-intrusive manner. Possibly, check if the plist is binary, and if it is, convert the plist to xml in a new plist, and read from that file?
