### ISSUE TITLE
Alfred-Extras/Workflows/Wolfram|Alpha.alfredworkflow Result Categories Suggestion

### ISSUE THREAD

**Issue by joech4n** [TylerEich/Alfred-Extras#29]
Hi Tyler, thanks for the amazing script!

I was trying to get option to copy one of the results from one of the other answer groups (like "Unit conversions") for a query like `21341 bytes per 10 seconds`. I believe your version currently only returns results from the "Result" group, so I made [the following edit to the workflow](https://gist.github.com/joech4n/11961dc2f76162c82286).

Would you be interested in adding it (or something a bit more refined) to your workflow?

Thanks again for your brilliant work! 👌💯

**Comment by TylerEich** [comment]
Glad you like it 😎  I'm busy the next few days, but I have a note to circle back to this issue. If you find the time, it would help me to attach a screenshot of this workflow in action. Thanks for contributing 💪💯🔥

**Comment by joech4n** [comment]
I made updates to return the results in the list, but I'd like a way to copy the results from there. Here is a screenshot! Thanks again for your work on this!

![](https://s3.amazonaws.com/f.cl.ly/items/1p3h1M0e0x0z1V2G302K/Screen%20Shot%202016-01-29%20at%204.06.53%20PM.png?v=f9af0da0)

**Comment by joech4n** [comment]
I think I figured it out.

I just needed to set the `arg` attribute in `result()` (I used a string like this: `"$q = $result_string"`, where `$result_string` is the result from WolframAlpha). Since this gets passed as an input to the next workflow (**clipboard.php**). Then I changed **clipboard.php** to just keep passing it forward into the clipboard.

Diff: https://gist.github.com/joech4n/f5cb98a323bb0c9cc1da

**Comment by TylerEich** [comment]
I like your changes and I want them in the codebase.

Unfortunately, I'm busier than I originally expected to be. I don't have time to publish an update to the codebase right now.

If you're up for it, you're absolutely welcome to fork the codebase and publish the changes under your name. Otherwise, it'll have to wait until I have time free to update this.
