### ISSUE TITLE
Color Picker is broken in Alfred 3

### ISSUE THREAD

**Issue by hugomd** [TylerEich/Alfred-Extras#31]
It pops up but doesn't return the colour properly.

**Comment by TylerEich** [comment]
Thanks for reporting this. If I remember correctly, this was an issue I ran into with Alfred 2 after an OS X update 😕

Which version of OS X are you using?

I'll do my best to fix this issue, but I don't have much time to devote to it. I recommend using [Sip](http://sipapp.io) in the meantime 👍

**Comment by hugomd** [comment]
I'm using El Capitan, 10.11.4.
Thanks 👍

**Comment by Benjamski** [comment]
This was a total bummer! I use this workflow way more than I realized until I noticed it wasn't working 😞 

El Capitan 10.11.3 

Please let me know if there's anything I can do contribute to the process @TylerEich  and thanks for the sip suggestion!

**Comment by TylerEich** [comment]
Thanks Ben. I have a (very early) alpha version of Colors 3 that I'm working on. I will let you know when I post that 👍

Tyler Eich • eichtyler@gmail.com

**Comment by danielecook** [comment]
Any update on color picker? You take donations (-:   ?

This is such a great workflow I'd love to have it working again. Haven't been able to get it running with Alfred 3.

**Comment by TylerEich** [comment]
I can't make any promises...I've started doing professional web development and don't have a ton of time to support my Alfred projects anymore. And since I don't use a lot of these tools myself anymore, I'm not very motivated to keep working on them.

Thanks for letting me know you're still interested. There's a lot of stuff I'd need to tackle to make it a reality. If I get a chance to figure out Xcode again, and finish learning Swift, and write the rest of color parsing library I planned for this update, and learn the Alfred 3 API, and release the update, I'll be sure to let you know :+1:

**Comment by hugomd** [comment]
@TylerEich Thanks for the update! 😊

**Comment by fuelingtheweb** [comment]
For anyone interested, this is actually an easy fix.

- In Alfred Preferences under Workflows, right click on Colors and click "Open in Finder".
- Then open colors.php in your editor.
- Around line 95 in the osascript, change "Alfred 2" to be "Alfred 3".
- Save the file and you should be good to go.

**Comment by danielecook** [comment]
There is no file called 'colors.php'...?

**Comment by fuelingtheweb** [comment]
@danielecook Here's my export that works with Alfred 3. I hope that helps.

[Colors.alfredworkflow.zip](https://github.com/TylerEich/Alfred-Extras/files/966261/Colors.alfredworkflow.zip)

**Comment by danielecook** [comment]
@fuelingtheweb Thank you so much! This works great!

**Comment by hugomd** [comment]
@fuelingtheweb Much appreciated 👍

**Comment by hugomd** [comment]
Closing as @fuelingtheweb has fixed the issue, at least on my end!

**Comment by cucumbur** [comment]
That did the trick! Sweet, thanks @fuelingtheweb

**Comment by fuelingtheweb** [comment]
Here's an update to the workflow that ensures it works with Alfred 3. I ran into an issue where if you no longer have `~/Library/Caches/com.runningwithcrayons.Alfred-2/`, the workflow would break again. So, this fixes that issue.

[Colors-alfred-3.alfredworkflow.zip](https://github.com/TylerEich/Alfred-Extras/files/1231174/Colors-alfred-3.alfredworkflow.zip)
