### ISSUE TITLE
Possible to use Node? 

### ISSUE THREAD

**Issue by kevinSuttle** [TylerEich/Alfred-Extras#32]
cc @Qix-

Wondering if the two can work together. https://www.npmjs.com/package/color

**Comment by TylerEich** [comment]
Thanks for the suggestion, but OS X doesn't include a copy of NodeJS built in. Additionally, this package only parses web formats. My workflow parses Swift and Objective-C formats as well

Tyler Eich • eichtyler@gmail.com

**Comment by kevinSuttle** [comment]
Oh right. However, he does have this one as well: https://github.com/Qix-/color-convert/issues/30 https://github.com/Qix-/color-convert/issues/26
